name: Ba-dua Coverage Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: Build, Test, and Generate Ba-dua Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Maven build and tests
        run: mvn -B verify -P ba-dua-coverage

      - name: Upload Ba-dua Coverage Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ba-dua-coverage-report
          path: bookkeeper-server/target/badua.xml