name: PIT Mutation Testing Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-mutation-test:
    name: Build, Test, and Run PIT Mutation Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run PIT Mutation Testing
        run: mvn -B verify -P mutation-testing

      - name: Upload PIT Mutation Testing Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pit-mutation-testing-report
          path: bookkeeper-server/target/pit-reports/**